### ISSUE TITLE
Custom Build of Only Radio buttons doesn't work (1.4.5)

### ISSUE THREAD

**Issue by smbgood** [jquery/jquerymobile.com#115]
When I include the full jQuery mobile js and css files, the radio buttons show up as expected.

Doing a custom build, selecting 'Checkboxes and Radio buttons' and 'Control Groups' and then including the resulting files, I do not see the same resulting styles and functionality as when I include the full jQuery mobile.

For reference, these were the other boxes that got checked when I selected the two above: 
jqmData
Namespace
Virtual Mouse(vmouse) Bindings
Widget Factory
Form Reset
Path Helpers
First & Last Classes

If I was starting from scratch, it wouldn't be a problem, but the default styles that jQM applies interfere with the look and feel of the webpage I'm working on. Optimally, I'd just like to be able to pick and choose which pieces to include.

**Comment by gabrielschulhof** [comment]
We do indeed have a bug. controlgroup should depend on page because it accesses the page prototype. This causes an exception during the instantiation of the controlgroup. Nevertheless, you can work around the issue by producing the markup for the controlgroup yourself, and instantiating only the checkboxes. Additionally, if you wish to create a horizontal controlgroup, you must also remove the icon position class ```ui-btn-icon-left``` from the checkbox's label to avoid having space reserved for the icon:

http://jsbin.com/sigenu/3/

I'm going to close this issue because in 1.5.0 we will have a completely different implementation of controlgroup which should not exhibit this issue.

**Comment by smbgood** [comment]
@gabrielschulhof 

Thanks for the quick reply, unfortunately, not exactly what I'm looking for. The jsbin you linked to has some problems: when you click a checkbox, the label slides to the right and there's some empty space to the left of it. Also, no check appears.

**Comment by arschmitz** [comment]
@smbgood a better work around for this http://jsbin.com/riteyo/3/edit?html,js,output just set the 2 missing properties your self.
