### ISSUE TITLE
Builder 404 link

### ISSUE THREAD

**Issue by marothyzsolt** [jquery/jquerymobile.com#158]
If I select any version just infinity loading:
https://jquerymobile.com/download-builder/

For example this link:
https://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js

**Comment by KevynTD** [comment]
It's been weeks since it was like this, I thought they would have solved it but not yet, so I came to see if anyone had already reported. On July 4 I'm sure it worked, because I did a test. The https://jquerymobile.com/download-builder/ page gets an infinite loading, and I do not have the options to customize my download.

**Comment by creatorisback** [comment]
Page has infinite loading, please fix this

**Comment by mgol** [comment]
The Builder should work now.
